<!DOCTYPE html>
<title>register</title>

<!-- register form -->
<section>
   <div>name: <input name="name" id="name" type="text" autofocus></div>
   <div>phone:<input name="phone" id="phone" type="tel"></div>
   <div>email:<input name="email" id="email" type="email"></div>
   <div>age:  <input name="age" id="age" type="range" value=20></div>
   <div>gender:</div>
   <div>conutry:</div>
   <div>city in China</div>
   <div>profession:</div>
   <div><button value="submit" onclick="submit();return false;"></button></div>
</section>

<!-- javascript -->
<script type="text/javascript">
  function submit()
  {
      Location.href="http://www.sogou.com";
  }
</script>
